name: "PR Checks for feature branches"
on:
  pull_request:
    types:
      - opened        # initially opened
      - reopened      # closed then opened again
      - synchronize   # any changes pushed
    branches:
      - "feature/*"
    paths-ignore: # Only run checks on changes to code
      - "**/docs/*"
      - "*/README.md"

jobs:
  build:
    name: "Setup and Build Project (Feature)"
    runs-on: [ubuntu-22.04]
    if: github.event.pull_request.draft == false # ignore draft pull requests
#    env:
#
#    outputs:
#
    steps:
      - name: "Checkout Project"
        uses: actions/checkout@v4
      - name: "Setup Java 21"
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '21'
      - name: "Setup Gradle"
        uses: gradle/actions/setup-gradle@v3

      - name: "Setup Secrets"
        run: |
          touch ./secrets.properties
          touch ./stripe-secrets.properties
          touch ./api/secrets.properties

      - name: "Build: Assemble and Test entire project"
        run: ./gradlew build

#      - run: ./gradlew generate coverage report, upload test/coverage reports
