name: "CD / Android Release Builds"
on:
  push:
    branches:
      - main
    paths: # Only run checks on changes api to code or api dependencies
      - "api/**/*"
      - "core/entities/**/*"

jobs:
  build:
    name: "Setup and Build Project"
    runs-on: [ubuntu-22.04]
    if: github.event.pull_request.draft == false # ignore draft pull requests
#    env:
#
#    outputs:
#
    steps:
      - name: "Checkout Project"
        uses: actions/checkout@v4
      - name: "Setup Java 21"
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '21'
      - name: "Setup Gradle"
        uses: gradle/actions/setup-gradle@v3

      - name: "Setup Secrets"
        uses: ./.github/actions/setup-secrets

      - name: "Build: Assemble and Test API"
        run: |
          ./gradlew :api:build

#      - run: ./gradlew generate coverage report, upload test/coverage reports

      - name: "Bundle: Generate Fat-JAR"
        run: ./gradlew :api:buildFatJar

#      - name: "Upload: Send Release to GCloud Artifact Repository"
