name: "CI / API Builds"
#
on:
  pull_request:
    types:
      - opened        # initially opened
      - reopened      # closed then opened again
      - synchronize   # any changes pushed
    branches:
      - main
    paths: # Only run checks on changes api to code or api dependencies
      - "api/**/*"
      - "core-entities/**/*"
      - "core-data-dtos/**/*"

# TODO: Include version input

jobs:
  build:
    name: "Setup and Build Project"
    runs-on: [ubuntu-22.04]
    if: github.event.pull_request.draft == false # ignore draft pull requests
#    env:
#
#    outputs:
#
    steps:
      - name: "Checkout Project"
        uses: actions/checkout@v4
      - name: "Setup Java 21"
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '21'
      - name: "Setup Gradle"
        uses: gradle/actions/setup-gradle@v3
      - name: 'Setup OpenTofu'
        uses: opentofu/setup-opentofu@v1
        with:
          tofu_version: '1.9.1'

      - name: "Setup Secrets"
        uses: ./.github/actions/setup-secrets

      - name: 'Tofu Plan'
        run: |
          tofu -chdir=api init
          tofu -chdir=api plan \
            --output-file tofu-plan.json \
            --format json
      - name: 'Upload: Tofu Plan'
        uses: actions/upload-artifact@v4
        with:
          name: tofu-plan.json
          path: api/tofu-plan.json

      - name: "Build: Assemble and Test API"
        run: |
          ./gradlew :api:build

#      - run: ./gradlew generate coverage report, upload test/coverage reports

      - name: "Bundle: Generate Fat-JAR"
        run: ./gradlew :api:buildFatJar

      - name: "Upload: Send JARs to GitHub"
        uses: actions/upload-artifact@v4
        with:
          name: app-android-debug
          path: api/build/libs/XYZ-API-0.1.0.jar
