name: "CD / Android Release Builds"
on:
  push:
    branches:
      - main
    paths-ignore: # Only run checks on changes to code
      - "**/docs/*"
      - "*/README.md"

jobs:
  build:
    name: "Setup and Build Project"
    runs-on: [ubuntu-22.04]
    if: github.event.pull_request.draft == false # ignore draft pull requests
#    env:
#
#    outputs:
#
    steps:
      - name: "Checkout Project"
        uses: actions/checkout@v4
      - name: "Setup Java 17"
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '17'
      - name: "Setup Gradle"
        uses: gradle/actions/setup-gradle@v3

      - name: "Build: Assemble and Test entire project"
        run: ./gradlew :app-android:buildRelease

#      - run: ./gradlew generate coverage report, upload test/coverage reports

      - name: "Bundle: Generate AABs"
        run: ./gradlew :app-android:bundleRelease

#      - name: "Upload: Send Release to Google Play Store"
#        uses: google-github-actions/upload-google-play@main
#        with:
#          serviceAccountJson: ${{ secrets.GOOGLE_PLAY_JSON }}
#          packageName: com.example.myapp
#          bundleFile: app/build/outputs/bundle/release/app-release.aab
#          track: internal

      - name: "Upload: Send AABs to GitHub"
        uses: actions/upload-artifact@v4
        with:
          name: app-android-release
          path: app-android/build/outputs/bundle/release/app-android-release.aab
