name: "CI / API Builds"
#
on:
  pull_request:
    types:
      - opened        # initially opened
      - reopened      # closed then opened again
      - synchronize   # any changes pushed
    branches:
      - main
    paths: # Only run checks on changes api to code or api dependencies
      - "api/**/*"
      - "core/entities/**/*"

# TODO: Include version input

jobs:
  build:
    name: "Setup and Build Project"
    runs-on: [ubuntu-22.04]
    if: github.event.pull_request.draft == false # ignore draft pull requests
#    env:
#
#    outputs:
#
    steps:
      - name: "Checkout Project"
        uses: actions/checkout@v4
      - name: "Setup Java 17"
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '17'
      - name: "Setup Gradle"
        uses: gradle/actions/setup-gradle@v3

      - name: "Build: Assemble and Test API"
        run: |
          ./gradlew :api:build

#      - run: ./gradlew generate coverage report, upload test/coverage reports

      - name: "Bundle: Generate Fat-JAR"
        run: ./gradlew :api:buildFatJar

#      - name: "Upload: Send Release to GCloud Artifact Repository"

      - name: "Upload: Send JARs to GitHub"
        uses: actions/upload-artifact@v4
        with:
          name: app-android-debug
          path: api/build/libs/XYZ-API-0.1.0.jar
