name: "CI / Build Static Website"
#
on:
  push:
    branches:
      - main

jobs:
  build:
    name: "Setup and Build Project"
    runs-on: [ubuntu-22.04]
#    env:
#
#    outputs:
#
    steps:
      - name: "Setup Java 21"
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '21'
      - name: "Setup Gradle"
        uses: gradle/actions/setup-gradle@v3
        
      - name: "Checkout Project"
        uses: actions/checkout@v4
        with:
          path: 'XYZ'

      - name: "Build: Static Website"
        run: |
          cd XYZ
          touch stripe-secrets.properties
          ./gradlew :website:run --args="--out build/static-site"

      - name: "Checkout Static Site"
        uses: actions/checkout@v4
        with:
          path: "XYZ-static-site"
          repository: 'Pointyware/XYZ-static-site'
          token: ${{ secrets.XYZ_STATIC_SITE_UPLOAD_TOKEN }}

      - name: "Copy Static Site"
        run: |
          pwd
          cd XYZ-static-site
          rm -rf ./*
          cp -r ../XYZ/website/build/static-site/* ./

      - name: "Commit Static Site"
        run: |
          git commit -m "Update static site" --allow-empty
          git push
